"""empty message

Revision ID: b5332a7c0acf
Revises: 0f9a009a59db
Create Date: 2022-05-10 10:31:07.817104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5332a7c0acf'
down_revision = '0f9a009a59db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IngredientsInRecipe', sa.Column('measurement_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IngredientsInRecipe', 'measurement_type')
    # ### end Alembic commands ###
