"""empty message

Revision ID: 3619a740747f
Revises: bd61bc53ff2f
Create Date: 2022-05-12 09:14:56.156971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3619a740747f'
down_revision = 'bd61bc53ff2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('imgURL', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'imgURL')
    # ### end Alembic commands ###
