"""empty message

Revision ID: 701e25827bc6
Revises: 0bb0c09f14da
Create Date: 2022-05-16 15:31:06.030629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701e25827bc6'
down_revision = '0bb0c09f14da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hearts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heart_num', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hearts')
    # ### end Alembic commands ###
