"""empty message

Revision ID: 0bb0c09f14da
Revises: 3619a740747f
Create Date: 2022-05-16 10:06:39.073205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb0c09f14da'
down_revision = '3619a740747f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookCounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tried_dish', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookCounts')
    # ### end Alembic commands ###
